apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-br67
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-br67
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-br67
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-br67
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-br67
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-xzlg-tenant/appstudio/dc-metro-map-br67@sha256:0de3185617df0dae0f8b529b4e1f2fe175c32754d7d03376ecf0dfce3ae78148
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
